management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always
        logfile:
            external_file: ./target/logs/library.log
    health:
        defaults:
            enabled: true

    # https://stackoverflow.com/questions/56555501/registering-hystrix-concurrency-strategy-fails-after-migrating-to-spring-boot-2
    metrics:
        binders:
            hystrix:
                enabled: false

logging:
    file: ./target/logs/library.log
    level:
        ROOT: INFO
        org:
            hibernate:
                stat: INFO
        com.netflix.hystrix: DEBUG

spring:
    data:
        rest:
            basePath: /datarest

    main:
        allow-bean-definition-overriding: true

    datasource:
        platform: postgres
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: pswd
        # driver-class-name: ${DB_DRIVER}
        # url: ${DB_URL}
        # username: ${DB_USERNAME}
        # password: ${DB_PASSWORD}
        schema:
            classpath: schema.sql
        data:
            classpath: data.sql
        initialization-mode: always

    jpa:
        generate-ddl: false
        show-sql: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
                generate_statistics: false

    messages:
        basename: bundle
        encoding: UTF-8

    jmx:
        enabled: true

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 15000

