version: '3'
services:
  library-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://postgresql:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=pswd
      - WAIT_FOR=postgresql:5432
    networks:
      - nw
  postgresql:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pswd
      - POSTGRES_DB=postgres
    networks:
      - nw
networks:
  nw: