localization:
    language: ru
    country: RU

jwt:
#    The secret key you've used is too short. If you are using HS256 which is HMAC with SHA-256 needs at least 256 bits or larger MUST be used with the HS256 algorithm.
    secret: VGhlIHNlY3JldCBrZXkgeW91J3ZlIHVzZWQgaXMgdG9vIHNob3J0LiBJZiB5b3UgYXJlIHVzaW5nIEhTMjU2IHdoaWNoIGlzIEhNQUMgd2l0aCBTSEEtMjU2IG5lZWRzIGF0IGxlYXN0IDI1NiBiaXRzIG9yIGxhcmdlciBNVVNUIGJlIHVzZWQgd2l0aCB0aGUgSFMyNTYgYWxnb3JpdGhtLg==

appsession:
    user: User01

logging:
    level:
        org:
            hibernate:
                stat: debug

spring:
    h2:
        console:
#            enabled: true
            path: /h2

    datasource:
        url: jdbc:h2:mem:testdb
        schema:
            classpath: schema.sql
        data:
            classpath: data.sql
        initialization-mode: always

    jpa:
        generate-ddl: false
        show-sql: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
                generate_statistics: false

    batch:
        initialize-schema: always

    messages:
        basename: bundle
        encoding: UTF-8
