localization:
    language: ru
    country: RU

appsession:
    user: User01

spring:
    h2:
        console:
            enabled: true
            path: /h2

    datasource:
        url: jdbc:h2:mem:testdb
        initialization-mode: always
        data: data.sql

    jpa:
        generate-ddl: false
        show-sql: true
        hibernate:
            ddl-auto: none

    shell:
        interactive:
            enabled: true

    messages:
        basename: bundle
        encoding: UTF-8
